---
- name: 사용자 추가
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - var/secret.yml
  tasks:
    - name: 사용자 추가 ehdwkr
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
  
      with_items: 
        "{{ newusers }}"